### PR TITLE
UI templates for the store manager application

### PR DESCRIPTION
**Pull request by mariamiah**
@Rwothoromo  @habatkasa @BarnaTB @RLubwama @codjoero @masete @bekeplar @RLubwama
@mwinel @armstrongsouljah

### CODE REVIEW

**Comment by mariamiah** [comment]
https://mariamiah.github.io/Store-Manager-Challenge1/

**Comment by armstrongsouljah** [comment]
Hey Maria. Your registration form is too shunk on the phone. Let grow to the full width of the viewport on small screens. The the image can be either gotten rid of or turned I to a background.

**Comment by missvicki** [comment]
Looks good, i think you should make logout one word rather than have it broken down


https://mariamiah.github.io/Store-Manager-Challenge1/UI/admin_dashboard.html?

**Comment by bekeplar** [comment]
Good work Maria but also consider small screens

**Comment by mariamiah** [comment]
Okay.,thank you all  let me adjust the pages

**Comment by RLubwama** [comment]
Great work mariam,your UIs are fine and great

**Pull request merged**
